"""The agent brain — a LangGraph that reviews a PR diff.

Topology (fan-out / fan-in):

            ┌─ code_quality ─┐
    START ──┼─ test_coverage ─┼──▶ supervisor ──▶ END
            └─ docs ─────────┘

The three reviewer nodes run in parallel (one superstep); each writes to its own
state key so there are no concurrent-write conflicts. The supervisor node has
all three as parents, so LangGraph runs it only after they all complete, then it
synthesizes the final Markdown comment.

Public contract (do not change — `main.py` depends on it):
    run_review(pr_context: PRContext) -> str   # Markdown for the PR comment
"""

from __future__ import annotations

from functools import lru_cache
from typing import TypedDict

from langgraph.graph import END, START, StateGraph

from agents.code_quality import run_code_quality_agent
from agents.docs_agent import run_docs_agent
from agents.supervisor import run_supervisor
from agents.test_coverage import run_test_coverage_agent


class PRContext(TypedDict):
    """Everything the agents need about one pull request."""

    repo: str          # "owner/repo"
    number: int
    title: str
    body: str
    files: list[dict]   # see github_utils.collect_pr_files
    diff: str           # see github_utils.build_diff_text
    instructions: str   # optional, from the repo's .arbiter.yml (may be "")
    repo_context: str   # optional, RAG-retrieved repo excerpts (may be "")


class ReviewState(TypedDict):
    """Mutable state threaded through the graph."""

    diff: str
    instructions: str
    repo_context: str
    code_feedback: str
    test_feedback: str
    docs_feedback: str
    review: str


# --- Nodes: each returns a partial state update ---

def _code_node(state: ReviewState) -> dict:
    return {"code_feedback": run_code_quality_agent(
        state["diff"], state.get("instructions", ""), state.get("repo_context", ""))}


def _test_node(state: ReviewState) -> dict:
    return {"test_feedback": run_test_coverage_agent(
        state["diff"], state.get("instructions", ""), state.get("repo_context", ""))}


def _docs_node(state: ReviewState) -> dict:
    return {"docs_feedback": run_docs_agent(
        state["diff"], state.get("instructions", ""), state.get("repo_context", ""))}


def _supervisor_node(state: ReviewState) -> dict:
    return {
        "review": run_supervisor(
            state["code_feedback"],
            state["test_feedback"],
            state["docs_feedback"],
            state.get("instructions", ""),
        )
    }


@lru_cache(maxsize=1)
def _compiled_graph():
    builder = StateGraph(ReviewState)
    builder.add_node("code_quality", _code_node)
    builder.add_node("test_coverage", _test_node)
    builder.add_node("docs", _docs_node)
    builder.add_node("supervisor", _supervisor_node)

    # Fan out from START to all three reviewers (parallel).
    builder.add_edge(START, "code_quality")
    builder.add_edge(START, "test_coverage")
    builder.add_edge(START, "docs")

    # Fan in: supervisor waits for all three before running.
    builder.add_edge("code_quality", "supervisor")
    builder.add_edge("test_coverage", "supervisor")
    builder.add_edge("docs", "supervisor")
    builder.add_edge("supervisor", END)

    return builder.compile()


def run_review(pr_context: PRContext) -> str:
    """Run the review graph over a PR and return the Markdown comment body."""
    diff = pr_context["diff"].strip()
    if not diff:
        return (
            "## 🤖 Arbiter — PR Review\n\n"
            "No reviewable text diff was found (binary-only or empty change set)."
        )

    instructions = pr_context.get("instructions", "")
    repo_context = pr_context.get("repo_context", "")
    result = _compiled_graph().invoke(
        {"diff": diff, "instructions": instructions, "repo_context": repo_context}
    )
    verdict = result["review"]

    custom = " · applied repo `.arbiter.yml`" if instructions.strip() else ""
    rag = " · 🔍 repo-aware" if repo_context.strip() else ""
    return (
        "## 🤖 Arbiter — PR Review\n\n"
        f"_Reviewed `{pr_context['repo']}#{pr_context['number']}` — "
        f"{len(pr_context['files'])} file(s) changed{custom}{rag}._\n\n"
        f"{verdict}\n\n"
        "<sub>Generated by Arbiter (code-quality · test-coverage · docs agents → supervisor).</sub>"
    )
